version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    depends_on:
      - fluentd
    
  fluentd:
    image: fluent/fluentd
    container_name: fluentd
    # volumes:
    #   - ./logs:/fluentd/log
    ports:
      - "24224:24224"
          